name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Clone the repo
      - name: Clone repository
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Type check
      - name: Type check
        run: npm run check

      # Build the static site (Vite outputs to dist/ by default)
      - name: Create static build
        run: npm run build

      # Verify build output
      - name: Verify build output
        run: |
          echo "Build completed. Contents of dist directory:"
          ls -la dist/
          echo "Total size:"
          du -sh dist/

      # Upload the artifact for other stages to use
      - name: Share artifact in github workflow
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Download the build artifact
      - name: Get build artifact
        uses: actions/download-artifact@v4
        with:
          name: build
          path: dist

      # Setup the AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Verify deployment files
      - name: Verify deployment files
        run: |
          echo "Files to be deployed:"
          ls -la dist/
          echo "Checking for index.html:"
          if [ -f "dist/index.html" ]; then
            echo "✓ index.html found"
          else
            echo "✗ index.html missing!"
            exit 1
          fi

      # Copy the files from /dist to s3 bucket
      - name: Deploy static site to S3 bucket
        run: |
          echo "Deploying to S3 bucket: ${{ secrets.S3_BUCKET_NAME }}"
          aws s3 sync . s3://${{ secrets.S3_BUCKET_NAME }} --delete --exact-timestamps
          echo "Deployment completed successfully!"
        working-directory: dist
